baseURL = "https://amihan.gitlab.io/cloudblocks/docs/cloudblocks-storage-doc"
languageCode = "en-us"
title = "CloudBlocks Storage Platform Admin Guide"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	description = "Amihan Documentations"
	copyright = "Amihan Global Solutions"

	# Repository
	provider = "GitHub"
	repo_url = ""

	version = "1.2"
	logo = "images/cb.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = [
		"stylesheets/cloudblocks.css"
	]
	# custom_js  = ["buzz.js"]

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
		primary = "teal"
		accent  = "teal"

	[params.font]
		text = "Roboto Light"
		code = "Ubuntu Mono"

[[menu.main]]
	name   = "Overview"
	url    = "/"
	weight = 5

[[menu.main]]
	name   = "Accessing CloudBlocks Storage"
	url    = "accessing-cloudblocks-storage/"
	weight = 10


[[menu.main]]
	name   = "Dashboard"
	url    = "dashboard/"
	weight = 20

[[menu.main]]
	name   = "Nodes"
	url    = "nodes/"
	weight = 30

[[menu.main]]
	name   = "Pools"
	url    = "pools/"
	weight = 40

[[menu.main]]
	name   = "Block Storage"
	url    = "block-storage/"
	weight = 50

[[menu.main]]
	name   = "Object Storage"
	url    = "object-storage/"
	weight = 60

[[menu.main]]
	name   = "Filesystem"
	url    = "filesystem/"
	weight = 70

[[menu.main]]
	name   = "Glossary"
	url    = "glossary/"
	weight = 80

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
